name: app-server
services:
  mysql:
    image: mysql:8.4
    container_name: app-mysql
    restart: unless-stopped
    environment:
      #root账号（只用于初始化/管理,业务用普通用户)
      MYSQL_ROOT_PASSWORD: "201108xxc"
      #自动创建数据库 + 普通用户
      MYSQL_DATABASE: app_db
      MYSQL_USER: app
      MYSQL_PASSWORD: "123456"
      TZ: UTC
    ports:
      - "7788:3306"
    volumes:
      #初始化SQL：会在首次创建数据卷时自动执行
      - ./migrations:/docker-entrypoint-initdb.d:ro
      #数据持久化
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      #mysqladmin ping:这个是MySQL官方镜像自带的
      #docker-compose里要用$$才能把$传给容器内部执行
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent" ]
      interval: 10s
      timeout: 5s
      retries: 5
